_

diff --git a/scripts/asdusend b/scripts/asdusend
--- a/scripts/asdusend
+++ b/scripts/asdusend
@@ -39,63 +39,12 @@ sendfile()
 
 end_defque()
 {
-	local retcode
+	local status
 
 	printf '^\n' | sockwrite -d 3 -s $VARDIR/$cts_name/usocket 
-	retcode=$?
-	logmsgtime "receive signal SIGUSR2 from quemngr (all deferred messages have been sent)"
-	logmsgtime "send \"^\" to iecproxy, return code $retcode" 
-}
-
-sigchld()
-{
-	local pid state code name
-	
-	trap '' CHLD
-	jobs -l >$jobslist
-	sync $jobslist
-	while read pid state; do
-		if test -z "$state" || /usr/bin/printf '%s' "$state" | grep -q '^Running\|^Stopped\|^Suspended'; then
-			continue
-		else
-			case "$state" in
-			Done*)
-				code=$(/usr/bin/printf '%s\n' "$state" | sed -n 's/^Done(\([0-9]\+\))$/\1/p')
-				
-				test -z $code && code=0
-				name=$(sed -n "s/$pid //p" $sendfiles)
-				
-				test -n "$name" && sed -i "/$pid/d" "$sendfiles"
-				sync $sendfiles
-
-				logmsgtime "sockwrite was completed pid = ${pid}, name = ${name}, state = ${state}, return code = ${code}" 
-				case "$code" in
-					0) 
-						/usr/bin/printf '%s\n' "$name $code $success" 
-						logmsgtime "file $name was transferred successfully, return code 0" 
-					;;
-					2) 
-						/usr/bin/printf '%s\n' "$name $code $fail" 
-						logmsgtime "connection with CTS lost, return code 2" 
-					;;
-					3) 
-						logmsgtime "all deferred messages have been sent, return code 3"
-					;;
-					*) 
-						/usr/bin/printf '%s\n' "$name $code $fail" 
-						logmsgtime "file $name was not delivered, return code ${code}"
-					;;
-				esac
-			;;
-			*)
-				true
-			;;
-			esac
-		fi
-	done <<-EOF
-		$(sed 's/^.* \([0-9].*\)/\1/' <$jobslist)	
-	EOF
-	trap 'sigchld' CHLD
+	status=$?
+	logmsgtime "receive signal SIGUSR2 from quemngr (all deferred messages have been sent), send \"^\" to iecproxy" 
+	logmsgtime "sockwrite return code $status" 
 }
 
 trap 'end_defque' USR2
@@ -106,13 +55,26 @@ while true; do
 		/usr/bin/printf '%s\n' "$filename 1 $confirm"
 		logmsgtime "File name $filename from quemngr received"
 		
-		trap '' CHLD
-
-		sendfile ./act/$filename & 
-		/usr/bin/printf '%s %s\n' $! $filename >>$sendfiles
-		sync $sendfiles
+		sendfile ./act/$filename
 		logmsgtime "Send file ./act/$filename to iecproxy" 
 		
-		trap 'sigchld' CHLD
+		status=$?
+		case "$status" in
+			0) 
+				/usr/bin/printf '%s\n' "$filename $status $success" 
+				logmsgtime "file $filename was transferred successfully, return code 0" 
+			;;
+			2) 
+				/usr/bin/printf '%s\n' "$filename $status $fail" 
+				logmsgtime "connection with CTS lost, return code 2" 
+			;;
+			3) 
+				logmsgtime "all deferred messages have been sent, return code 3"
+			;;
+			*) 
+				/usr/bin/printf '%s\n' "$filename $status $fail" 
+				logmsgtime "file $filename was not delivered, return code ${status}"
+			;;
+		esac
 	fi
 done
